DELETE FROM film_genre;
--INSERT INTO PUBLIC.FILM_GENRE (GENRE_ID, GENRE_NAME)
--VALUES (0, '-');
INSERT INTO PUBLIC.FILM_GENRE (GENRE_ID, GENRE_NAME)
VALUES (1, 'Комедия');
INSERT INTO PUBLIC.FILM_GENRE (GENRE_ID, GENRE_NAME)
VALUES(2, 'Драма');
INSERT INTO PUBLIC.FILM_GENRE (GENRE_ID, GENRE_NAME)
VALUES(3, 'Мультфильм');
INSERT INTO PUBLIC.FILM_GENRE (GENRE_ID, GENRE_NAME)
VALUES(4, 'Триллер');
INSERT INTO PUBLIC.FILM_GENRE (GENRE_ID, GENRE_NAME)
VALUES(5, 'Документальный');
INSERT INTO PUBLIC.FILM_GENRE (GENRE_ID, GENRE_NAME)
VALUES(6, 'Боевик');
DELETE FROM film_rating;
--INSERT INTO PUBLIC.FILM_RATING (RATING_ID, RATING_NAME)
--VALUES(0, '-');
INSERT INTO PUBLIC.FILM_RATING (RATING_ID, RATING_NAME)
VALUES(1, 'G');
INSERT INTO PUBLIC.FILM_RATING (RATING_ID, RATING_NAME)
VALUES(2, 'PG');
INSERT INTO PUBLIC.FILM_RATING (RATING_ID, RATING_NAME)
VALUES(3, 'PG-13');
INSERT INTO PUBLIC.FILM_RATING (RATING_ID, RATING_NAME)
VALUES(4, 'R');
INSERT INTO PUBLIC.FILM_RATING (RATING_ID, RATING_NAME)
VALUES(5, 'NC-17');